# Generated by Django 3.0.6 on 2020-06-09 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletter',
            options={'ordering': ['email'], 'verbose_name': 'NewsLetter', 'verbose_name_plural': 'NewsLetter'},
        ),
    ]
