# Generated by Django 3.0.6 on 2020-06-15 13:50

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('CityId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Citys',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('CountryId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32, unique=True)),
                ('Code', models.PositiveIntegerField(default=2)),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countrys',
            },
        ),
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to=settings.AUTH_USER_MODEL)),
                ('DealerId', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=32, unique=True)),
                ('Email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=32, unique=True)),
                ('CityId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealers.City')),
            ],
            options={
                'verbose_name': 'Dealer',
                'verbose_name_plural': 'Dealers',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddIndex(
            model_name='country',
            index=models.Index(fields=['name'], name='dealers_cou_name_e099c0_idx'),
        ),
        migrations.AddField(
            model_name='city',
            name='CountryId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealers.Country'),
        ),
        migrations.AddIndex(
            model_name='dealer',
            index=models.Index(fields=['name'], name='dealers_dea_name_81be76_idx'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['name'], name='dealers_cit_name_c4705a_idx'),
        ),
    ]
